using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using XFramework.Domain.Identity;
namespace XFramework.EntityFrameworkCore.Identity;
public sealed class XFrameworkIdentityDbContext(DbContextOptions<XFrameworkIdentityDbContext> options):IdentityDbContext<XFrameworkIdentityUser,IdentityRole<Guid>,Guid>(options)
{ public DbSet<User> ApplicationUsers => Set<User>(); public DbSet<Role> ApplicationRoles => Set<Role>(); public DbSet<UserRole> ApplicationUserRoles => Set<UserRole>(); public DbSet<UserPermission> ApplicationUserPermissions => Set<UserPermission>(); public DbSet<Permission> ApplicationPermissions => Set<Permission>(); public DbSet<RolePermission> ApplicationRolePermissions => Set<RolePermission>();
 protected override void OnModelCreating(ModelBuilder b){base.OnModelCreating(b); b.Entity<User>(e=>{e.ToTable("XfUsers");e.HasKey(x=>x.Id);e.Property(x=>x.UserName).HasMaxLength(100).IsRequired();e.HasIndex(x=>x.UserName).IsUnique();e.Property(x=>x.DisplayName).HasMaxLength(200);}); b.Entity<Role>(e=>{e.ToTable("XfRoles");e.HasKey(x=>x.Id);e.Property(x=>x.Name).HasMaxLength(100).IsRequired();e.HasIndex(x=>x.Name).IsUnique();e.Property(x=>x.DisplayName).HasMaxLength(200);}); b.Entity<Permission>(e=>{e.ToTable("XfPermissions");e.HasKey(x=>x.Id);e.Property(x=>x.Name).HasMaxLength(200).IsRequired();e.HasIndex(x=>x.Name).IsUnique();e.Property(x=>x.DisplayName).HasMaxLength(200);e.Property(x=>x.Description).HasMaxLength(500);}); b.Entity<UserRole>(e=>{e.ToTable("XfUserRoles");e.HasKey(x=>new{x.UserId,x.RoleId});e.HasOne(x=>x.User).WithMany().HasForeignKey(x=>x.UserId);e.HasOne(x=>x.Role).WithMany().HasForeignKey(x=>x.RoleId);}); b.Entity<RolePermission>(e=>{e.ToTable("XfRolePermissions");e.HasKey(x=>new{x.RoleId,x.PermissionId});e.HasOne(x=>x.Role).WithMany().HasForeignKey(x=>x.RoleId);e.HasOne(x=>x.Permission).WithMany().HasForeignKey(x=>x.PermissionId);}); b.Entity<UserPermission>(e=>{e.ToTable("XfUserPermissions");e.HasKey(x=>new{x.UserId,x.PermissionId});e.HasOne(x=>x.User).WithMany().HasForeignKey(x=>x.UserId);e.HasOne(x=>x.Permission).WithMany().HasForeignKey(x=>x.PermissionId);}); }
}
