using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using XFramework.Application.Events;
using XFramework.Domain.Entities;
using XFramework.Domain.Events;
using XFramework.EntityFrameworkCore.Outbox;
using Xunit;

namespace XFramework.IntegrationTests.Scenarios;

public sealed class OutboxAtomicPersistenceTests
{
    [Fact]
    public async Task Domain_event_and_outbox_should_commit_atomically()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var registry = new EventTypeRegistry();
        registry.Register(typeof(AtomicTestEvent));

        await using (var setupContext = CreateContext(connection, registry))
        {
            await setupContext.Database.EnsureCreatedAsync();
        }

        var aggregateId = Guid.NewGuid();

        await using (var context = CreateContext(connection, registry))
        {
            await using var transaction = await context.Database.BeginTransactionAsync();

            var aggregate = new AtomicTestAggregate(aggregateId, Guid.NewGuid());
            context.TestAggregates.Add(aggregate);

            // Capture the actual EventId from the domain event BEFORE save
            var actualEventId = aggregate.DomainEvents.First().EventId;

            await context.SaveChangesAsync();
            await transaction.CommitAsync();

            await using (var verification = CreateContext(connection, registry))
            {
                var savedAggregate = await verification.TestAggregates
                    .SingleAsync(x => x.Id == aggregateId);

                var outbox = await verification.OutboxMessages
                    .SingleAsync(x => x.EventId == actualEventId);

                Assert.Equal(aggregateId, Guid.Parse(outbox.AggregateId!));
                Assert.Equal("Integration.AtomicTest", outbox.EventType);
                Assert.Equal(1, outbox.EventVersion);
                Assert.Equal(OutboxMessageStatus.Pending, outbox.Status);
                Assert.Contains(actualEventId.ToString(), outbox.Payload, StringComparison.OrdinalIgnoreCase);
            }
        }
    }

    [Fact]
    public async Task Domain_event_and_outbox_should_rollback_together()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var registry = new EventTypeRegistry();
        registry.Register(typeof(AtomicTestEvent));

        await using (var setupContext = CreateContext(connection, registry))
        {
            await setupContext.Database.EnsureCreatedAsync();
        }

        var aggregateId = Guid.NewGuid();
        var eventId = Guid.NewGuid();

        await using (var context = CreateContext(connection, registry))
        {
            await using var transaction = await context.Database.BeginTransactionAsync();

            context.TestAggregates.Add(new AtomicTestAggregate(aggregateId, eventId));
            await context.SaveChangesAsync();

            await transaction.RollbackAsync();
        }

        await using (var verification = CreateContext(connection, registry))
        {
            Assert.Empty(await verification.TestAggregates.ToListAsync());
            Assert.Empty(await verification.OutboxMessages.ToListAsync());
        }
    }

    [Fact]
    public async Task Domain_event_should_remain_on_entity_when_save_fails()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var registry = new EventTypeRegistry();
        registry.Register(typeof(AtomicTestEvent));

        await using (var setupContext = CreateContext(connection, registry))
            await setupContext.Database.EnsureCreatedAsync();

        var aggregateId = Guid.NewGuid();

        await using var context = CreateContext(connection, registry);
        var aggregate = new AtomicTestAggregate(aggregateId, Guid.NewGuid());
        context.TestAggregates.Add(aggregate);

        // Capture the actual EventId generated by the domain event
        var actualEventId = aggregate.DomainEvents.First().EventId;

        // Add a duplicate EventId so the database unique constraint fails after
        // the domain event has also been converted into an Outbox row.
        // The domain event must not be lost on failure.
        await Assert.ThrowsAsync<DbUpdateException>(async () =>
        {
            context.OutboxMessages.Add(new OutboxMessage
            {
                Id = Guid.NewGuid(),
                EventId = actualEventId,
                EventType = "Duplicate",
                EventVersion = 1,
                Payload = "{}",
                Status = OutboxMessageStatus.Pending,
                RetryCount = 0,
                CreatedOnUtc = DateTime.UtcNow,
                OccurredOnUtc = DateTime.UtcNow
            });

            await context.SaveChangesAsync();
        });

        Assert.Contains(aggregate.DomainEvents, e => e.EventId == actualEventId);
    }

    private static AtomicOutboxTestDbContext CreateContext(
        SqliteConnection connection,
        EventTypeRegistry registry)
    {
        var options = new DbContextOptionsBuilder<AtomicOutboxTestDbContext>()
            .UseSqlite(connection)
            .Options;

        return new AtomicOutboxTestDbContext(options, registry);
    }
}

[EventType("Integration.AtomicTest", 1, "integration.atomic-test")]
public sealed record AtomicTestEvent(Guid AggregateId, Guid TestEventId) : DomainEvent;

public sealed class AtomicTestAggregate : Entity<Guid>
{
    private AtomicTestAggregate() { }

    public AtomicTestAggregate(Guid id, Guid eventId)
    {
        Id = id;
        AddDomainEvent(new AtomicTestEvent(id, eventId));
    }
}

public sealed class AtomicOutboxTestDbContext(
    DbContextOptions<AtomicOutboxTestDbContext> options,
    EventTypeRegistry registry)
    : DomainEventDbContext(options, registry)
{
    public DbSet<AtomicTestAggregate> TestAggregates => Set<AtomicTestAggregate>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<AtomicTestAggregate>(builder =>
        {
            builder.ToTable("AtomicTestAggregates");
            builder.HasKey(x => x.Id);
        });
        modelBuilder.ApplyConfiguration(new OutboxMessageConfiguration());
    }
}
