using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using XFramework.Application.DependencyInjection;
using XFramework.Blazor.Components;
using XFramework.Blazor.Localization;
using XFramework.Application.Contracts.Localization;
using XFramework.EntityFrameworkCore.Identity;
using XFramework.EntityFrameworkCore.DependencyInjection;
using XFramework.Infrastructure.DependencyInjection;
using XFramework.Infrastructure.Messaging.RabbitMQ.DependencyInjection;
var builder=WebApplication.CreateBuilder(args);
builder.Services.AddXFramework();
builder.Services.AddXFrameworkEntityFrameworkCore(builder.Configuration);
builder.Services.AddXFrameworkInfrastructure(builder.Configuration);
builder.Services.AddXFrameworkRabbitMQ(builder.Configuration);
builder.Services.AddIdentityCore<XFrameworkIdentityUser>(o=>{o.Password.RequiredLength=8;o.Password.RequireDigit=true;o.Password.RequireUppercase=true;o.Password.RequireLowercase=true;o.Password.RequireNonAlphanumeric=false;o.User.RequireUniqueEmail=false;}).AddRoles<IdentityRole<Guid>>().AddEntityFrameworkStores<XFrameworkIdentityDbContext>().AddSignInManager();
builder.Services.AddAuthentication(IdentityConstants.ApplicationScheme).AddIdentityCookies();
builder.Services.AddAuthorization();
builder.Services.AddRazorComponents().AddInteractiveServerComponents();
builder.Services.AddLocalization(o=>o.ResourcesPath="Localization/Resources");
builder.Services.AddScoped<ILocalizationService,BlazorLocalizationService>();
var cultures=new[]{"fa","en"};var localization=new RequestLocalizationOptions().SetDefaultCulture("fa").AddSupportedCultures(cultures).AddSupportedUICultures(cultures);
var app=builder.Build();app.UseRequestLocalization(localization);if(!app.Environment.IsDevelopment()){app.UseExceptionHandler("/Error");app.UseHsts();}app.UseHttpsRedirection();app.UseAuthentication();app.UseAuthorization();app.UseAntiforgery();app.MapStaticAssets();app.MapRazorComponents<App>().AddInteractiveServerRenderMode();app.Run();
