<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Radzen.Blazor" Version="11.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XFramework.Application.Contracts\XFramework.Application.Contracts.csproj" />
    <ProjectReference Include="..\XFramework.Application\XFramework.Application.csproj" />
    <ProjectReference Include="..\XFramework.EntityFrameworkCore\XFramework.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\XFramework.Infrastructure\XFramework.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
